# Generated by Django 3.1.7 on 2021-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_userevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
